"use client";

import { Check, Copy, ExternalLink, Link2, LoaderCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Page } from "@/components/ui/page";
import { ApiError } from "@/lib/api/errors";
import { affiliateService } from "@/modules/affiliate/services/affiliate.service";
import { useMockDatabase } from "@/modules/mock/hooks/use-mock-database";

export function GenerateLinkPage() {
  const [url, setUrl] = useState(""); const [result, setResult] = useState<string | null>(null); const [loading, setLoading] = useState(false); const { update } = useMockDatabase();
  const generate = async () => { let parsed: URL; try { parsed = new URL(url); } catch { toast.error("Link không hợp lệ"); return; } if (!parsed.hostname.endsWith("shopee.vn") && !parsed.hostname.endsWith("shp.ee")) { toast.error("Chỉ hỗ trợ link Shopee hợp lệ"); return; } setLoading(true); try { const response = await affiliateService.generate(url); if (!response.link) throw new Error(`Không tạo được link${response.code ? ` (${response.code})` : ""}`); setResult(response.link); update((db) => ({ ...db, links: [{ id: `LNK-${Date.now()}`, sourceUrl: url, affiliateUrl: response.link!, product: "Sản phẩm Shopee", status: "WORKING", createdAt: new Date().toISOString() }, ...db.links] })); toast.success("Tạo link cashback thành công"); } catch (error) { toast.error(error instanceof ApiError || error instanceof Error ? error.message : "Tạo link thất bại"); } finally { setLoading(false); } };
  const copy = async () => { if (!result) return; await navigator.clipboard.writeText(result); toast.success("Đã sao chép link"); };
  return <Page title="Tạo link cashback" description="Dán link Shopee để hệ thống tạo liên kết affiliate gắn với tài khoản của bạn."><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><div className="mb-5 flex size-12 items-center justify-center rounded-2xl bg-secondary text-primary"><Link2 /></div><label htmlFor="shopee-url" className="text-sm font-semibold">Link sản phẩm Shopee</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><Input id="shopee-url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://vn.shp.ee/... hoặc https://shopee.vn/product/..." /><Button size="lg" onClick={generate} disabled={loading || !url}>{loading ? <LoaderCircle className="animate-spin" /> : <Link2 />}Tạo link</Button></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Hệ thống xác thực domain và mở rộng short link trước khi tạo. Saffi không tham gia luồng tạo link.</p>{result && <div className="mt-6 rounded-2xl border border-success/20 bg-success-soft p-4"><div className="flex items-center gap-2 font-semibold text-success"><Check className="size-5" />Link đã sẵn sàng</div><p className="mt-3 break-all rounded-xl bg-white p-3 text-sm">{result}</p><div className="mt-3 flex flex-wrap gap-2"><Button onClick={copy}><Copy />Sao chép</Button><Button asChild variant="outline"><a href={result} target="_blank" rel="noreferrer"><ExternalLink />Mở link</a></Button></div></div>}</Card><Card className="h-fit"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-success-soft text-success"><ShieldCheck /></span><h2 className="font-semibold">Luồng an toàn</h2></div><ol className="mt-5 space-y-4 text-sm text-muted-foreground">{["Xác thực link thuộc Shopee", "Làm sạch URL sản phẩm", "Gắn Affiliate ID và mã tracking", "Lưu link để phục vụ đối soát"].map((item, index) => <li key={item} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-secondary text-xs font-bold text-primary">{index + 1}</span>{item}</li>)}</ol><div className="mt-6 rounded-xl bg-muted p-3 text-xs text-muted-foreground">Commission và cashback chỉ được xác nhận sau khi provider đối soát. Trang này không hiển thị số tiền ước tính khi API chưa cung cấp dữ liệu.</div></Card></div></Page>;
}
