"use client";
import Image from "next/image";
import { ExternalLink, PackageCheck, Percent, ShoppingBag, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, StatCard } from "@/components/ui/card";
import { Page } from "@/components/ui/page";
import { formatDateTime, formatVnd } from "@/lib/format";
import { useProduct } from "@/modules/products/hooks/use-products";

export function ProductDetailPage({ id }: { id: string }) { const query = useProduct(id); if (query.isLoading) return <Page title="Chi tiết sản phẩm"><div className="h-72 rounded-2xl skeleton" /></Page>; if (!query.data) return <Page title="Không tìm thấy sản phẩm"><p className="text-danger">Không thể tải sản phẩm.</p></Page>; const product = query.data; return <Page title="Chi tiết sản phẩm" description={`Shopee item ${product.itemId} · shop ${product.shopId}`} actions={<Button asChild variant="outline"><a href={product.productLink} target="_blank" rel="noreferrer"><ExternalLink />Mở trên Shopee</a></Button>}><Card><div className="grid gap-6 md:grid-cols-[220px_1fr]"><div className="relative aspect-square overflow-hidden rounded-2xl bg-muted">{product.imageUrl && <Image src={product.imageUrl} fill sizes="220px" alt={product.productName} className="object-cover" />}</div><div><p className="text-sm font-medium text-primary">{product.shopName}</p><h2 className="mt-2 text-xl font-bold leading-8 sm:text-2xl">{product.productName}</h2><p className="mt-4 text-3xl font-bold text-primary tabular">{formatVnd(product.price)}</p><p className="mt-3 text-sm text-muted-foreground">Cập nhật {formatDateTime(product.lastUpdate)}</p></div></div></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Đã bán" value={product.sales.toLocaleString("vi-VN")} icon={<ShoppingBag />} /><StatCard label="Đánh giá" value={product.rating} icon={<Star />} /><StatCard label="Tổng tỷ lệ" value={`${product.totalRatePercent}%`} icon={<Percent />} /><StatCard label="Commission" value={formatVnd(product.commission)} icon={<PackageCheck />} /></div><Card><h2 className="text-lg font-semibold">Chi tiết commission</h2><dl className="mt-5 grid gap-4 sm:grid-cols-3"><div><dt className="text-sm text-muted-foreground">Seller</dt><dd className="mt-1 font-semibold">{formatVnd(product.sellerComFinal)} · {product.sellerRatePercent}%</dd></div><div><dt className="text-sm text-muted-foreground">Shopee</dt><dd className="mt-1 font-semibold">{formatVnd(product.shoppeComFinal)} · {product.shopeeRatePercent}%</dd></div><div><dt className="text-sm text-muted-foreground">Cap</dt><dd className="mt-1 font-semibold">{formatVnd(product.capAfterRate)}</dd></div></dl></Card></Page>; }
